name: CD

on:
  workflow_run:
    workflows: ['CI'] # Allows you to trigger it manually from GitHub UI
    types: 
      - completed
jobs:
 build:
  runs-on: self-hosted

  steps:
    - name: Print Hello
      run: echo "Hello from GitHub Actions!"
    - name: pull docker image
      run: sudo docker pull guru506/ci.cd_pipeline:latest
    - name: check images
      run: sudo docker images
    - name: run the image
      run: sudo docker run -d -p 8080:8080 --name ci.cd_pipeline-container guru506/ci.cd_pipeline